### ISSUE TITLE
What is a license for this?

### ISSUE THREAD

**Issue by abelykh0** [majbthrd/stm32ecm#1]
What is a license for this?

**Comment by majbthrd** [comment]
It is open-source.  If you want to use it, read and follow the copyright terms shown in the source code.

**Comment by abelykh0** [comment]
I am sorry, I still cannot find the license. "open source" can be different (for example, GPL, LGPL, BSD-3, MIT, etc).

**Comment by majbthrd** [comment]
Look at each of the source files and read the copyright terms for each of them.  This is not new or different and must be done for any open source project.

It appears to me that you want a quick answer without even making this minor effort, and whilst I do not wish to indulge such behavior, it is wasting my time regardless.  The source code that I wrote and which Sergey Fetisov wrote are both under a MIT License; the STM32 driver and USB stack code is under their custom MCD-ST Liberty SW License Agreement V2.

Please bother look at the source code next time.  Compare the terms in the source code against the following popular options: https://opensource.org/licenses  No one in the world is obligated to use one of these, but it might be a place for you to start before asking questions.

**Comment by abelykh0** [comment]
Thank you for the detailed answer. Sorry for the misunderstanding.
